git secrets --add '(password|PASSWORD)\s*(:|=)\s*.+'
git secrets --add '(github_token|GITHUB_TOKEN)\s*(:|=)\s*.+'
git secrets --add '(token|TOKEN)\s*(:|=)\s*.+'
git secrets --add '(secret|SECRET)\s*(:|=)\s*.+'
git secrets --add 'ES_AUTH\s*:\s*(.+\s*.*):(.+\s*.*)$'
git secrets --add 'ES_HOST\s*:\s*(http|https)://(.+\s*.*):(.+\s*.*)@.+'
git secrets --add 'CLIENT_ID\s*:\s*[\w.]+'
git secrets --add 'CLIENT_SECRET\s*:\s*[\w.]+'